### ISSUE TITLE
Trinket slot functionality

### ISSUE THREAD

**Issue by MinecraftGuy926** [Strubbelkopp/Quiver#2]
Nyfsquivers trinket slot is perfect, but they overcomplicated everything else. This mod is perfect in its simplicity, but is lacking in trinket slot availablilty. Please add something similar to what nysquivers has. [fabric 1.20.1]

**Comment by Beez3-A** [comment]
yeah if it had a quiver trinket and actually renders on the slot then this would be perfect, such a cool mod

**Comment by Strubbelkopp** [comment]
Added compatibility for Trinkets now!

![2024-08-22_18 00 24](https://github.com/user-attachments/assets/2a6cc81a-c1e0-4598-ae0f-677d8f8445c8)

**Comment by Strubbelkopp** [comment]
Added compatibility with Trinkets now!
![2024-08-22_18 00 24](https://github.com/user-attachments/assets/79b5bf3f-2603-443d-937e-d88ca909b1aa)

**Comment by Beez3-A** [comment]
omg thank you so much ahahah! I was literally trying everything to do this myself, downloaded the source code and tried in intellj idea to add the code, but yeah it was not easy. Thanks so much!

**Comment by MinecraftGuy926** [comment]
Thank you!
